@startuml
left to right direction

together{
actor "Visiteur" as Visiteur
actor "Utilisateur" as Utilisateur
}

rectangle "Miniature"{
usecase "S'identifier" as Identifier
usecase "Créer un compte" as CreerCompte
usecase "Naviguer dans les recommendations" as NaviguerR
usecase "Naviguer dans les abonnements" as NaviguerA
usecase "Intéragir" as Interagir
usecase "Poster un message" as Poster
usecase "Liker un post" as Liker
usecase "Commenter un post" as Commenter
}

Utilisateur -left-|> Visiteur
Visiteur --- Identifier
Visiteur --- NaviguerR
Identifier <-.- CreerCompte : <<extends>>
Utilisateur --- NaviguerA
Utilisateur --- Interagir
Interagir <-.- Poster : <<extends>>
Interagir <-.- Liker : <<extends>>
Interagir <-.- Commenter : <<extends>>
@enduml